### PR TITLE
Progress with paket

### PR DESCRIPTION
**Pull request by forki**
Things I did:

* rename bootstrapper to paket.exe to enable magic mode (see https://fsprojects.github.io/Paket/bootstrapper.html#Magic-mode)
* Add Nuget.Config to clear all machine configs
* Remove package references from csproj - they are added automatically by the Paket.Restore.targets file
* Changed csproj to netstandard - we currently support only one framework (/cc @enricosada @cloudroutine)
* fixed a small bug in the targets - so you will need to call paket install again

### CODE REVIEW

**Comment by bchavez** [comment]
Hi @forki , thanks very much for your insight and help! I'll take a look at the changes :+1:

**Comment by bchavez** [comment]
Hi @forki ,

Thanks again for your PR. I really appreciate it. A few things tho:
* I'd like to continue targeting `net40`, so I'm not sure about removing `net40` framework.
* I've tried to use [`paket auto-restore off`](https://fsprojects.github.io/Paket/paket-auto-restore.html) and docs say it should remove the `<Import>` tag? But I'm finding it still persists when I supply `auto-restore off`. Does this setting not apply for **.NET Core** projects?

For now, I think I'd like to disable paket from adding the `<Import Project="..\.paket\Paket.Restore.targets" />` line and manage the dependency manually until we get multi-targeting in paket working. Any ideas on how to disable the injecting of `<Import>` in the new **csproj**?

Thanks,
Brian

**Comment by forki** [comment]
The mechanics of MSBuild have completely changed. You need the targets file in order to let paket do something at all. Without it you basically don't use paket at all. 
It's 100% different to MSBuild old style. I'm sorry we're not responsible for that change.

**Comment by cloudRoutine** [comment]
@bchavez I was looking at your project earlier with @forki, if you want to target `net40` you need to change your package dependencies, one of your csharp deps doesn't support `net40`



https://docs.microsoft.com/en-us/dotnet/articles/standard/library#net-platforms-support

You can make this happen but it's going to make your build more annoying to deal with. If your `paket.references` file for the project is empty, or it just doesn't have the specific dependency you want to manage manually in it, then it doesn't really matter if the import is in there or not.

The simplest thing might just to be to use links to src files in an additional project and use something like https://github.com/enricosada/dotnet-mergenupkg after you make two different ones, or throw a bunch of conditionals into your references so the framework conflicts don't keep happening.

You might as well kick up the framework so you don't have to worry about ifdef'n incompatible apis, but if you gotta support `net40` then I guess you'll have to slog through it

**Comment by bchavez** [comment]
Hi @forki @cloudRoutine ,

Thank you, both, for your insights. And thank you for your work on **Paket**. I totally understand Microsoft fuzzed with everything; I'm not happy with the new MS Build stuff either. Lots of drama. But, after some more testing with your suggestion:

> If your `paket.references` file for the project is empty, or it just doesn't have the specific dependency you want to manage manually in it, then it doesn't really matter if the import is in there or not.

It still kinda does tho... I am finding the `<Import>` still causses issues regardless if it's empty or not. It still blocks the `dotnet pack` workflow. Here's how:

* `git clone https://github.com/bchavez/Bogus --branch vs2017 .\Bogus2`
* `cd Bogus2\Source`
* `.\.paket\paket.exe install` (magic mode!!! thx @forki)
* `cd Bogus`
* `dotnet restore` :white_check_mark: ***success***
* `dotnet build` :white_check_mark: ***success***
* `dotnet pack` :white_check_mark: ***success*** (when `packet.references` contains **Newtonsoft**)
* `dotnet restore; dotnet pack` :x: ***fail*** (when `paket.references` is blank/empty)
```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Bogus -> C:\temp\Bogus2\Source\Bogus\bin\Debug\netstandard1.3\Bogus.dll
  Paket version 4.1.7
  Paket failed with:
        Specified references-file 'C:\temp\Bogus2\Source\Bogus/obj/Bogus.csproj.references' does not exist.
C:\temp\Bogus2\Source\.paket\Paket.Restore.targets(59,5): error MSB3073: The command ""C:\temp\Bogus2\Source\.paket\paket.exe" fix-nuspec file "obj\Bogus.0.0.0-localbuild.nuspec" references-file "C:\temp\Bogus2\Source\Bogus/obj/Bogus.csproj.references" " exited with code 1. [C:\temp\Bogus2\Source\Bogus\Bogus.csproj]
```
* `dotnet pack --include-symbols --include-source` :x: ***failure*** (when `paket.references` contains **Newtonsoft**)
```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Bogus -> C:\temp\Bogus2\Source\Bogus\bin\Debug\netstandard1.3\Bogus.dll
  Paket version 4.1.7
  Paket failed with:
        Specified file 'obj\Bogus.0.0.0-localbuild.nuspec;obj\Bogus.0.0.0-localbuild.symbols.nuspec' does not exist.
C:\temp\Bogus2\Source\.paket\Paket.Restore.targets(59,5): error MSB3073: The command ""C:\temp\Bogus2\Source\.paket\paket.exe" fix-nuspec file "obj\Bogus.0.0.0-localbuild.nuspec;obj\Bogus.0.0.0-localbuild.symbols.nuspec" references-file "C:\temp\Bogus2\Source\Bogus/obj/Bogus.csproj.references" " exited with code 1. [C:\temp\Bogus2\Source\Bogus\Bogus.csproj]
```

So, generating nuget packages with symbol info/sources doesn't work and `<Import>` still causes problems.

To be totally honest tho... I ***just want a way to disable*** paket's injection of `<Import>` into the `csproj` so everything works again and I'll handle everything else in F# FAKE. I would love to continue using Paket + F# FAKE because of the F# script generation/import still makes a lot of sense. I just don't want **paket** touching the `csproj`s when `paket.exe install` is called since I keep hitting a lot of friction.

Should just move `paket.dependencies` off to a sperate folder for F# FAKE usage? Will that stop **Paket** from touching the **csproj**s?

I'm sorry for being such a bug about this. This stuff is never easy. :cry: Let me know your thoughts. I (and my users) appreciate your help!

-Brian

**Comment by forki** [comment]
If you remove the paket.references file from the dotnetcore project folder
then it should ignore the csproj.

Am 06.04.2017 10:27 nachm. schrieb "Brian Chavez" <notifications@github.com
>:

Hi @forki <https://github.com/forki> @cloudRoutine
<https://github.com/cloudRoutine> ,

Thank you, both, for your insights. And thank you for your work on *Paket*.
I totally understand Microsoft fuzzed with everything; I'm not happy with
the new MS Build stuff either. Lots of drama. But, after some more testing
with your suggestion:

If your paket.references file for the project is empty, or it just doesn't
have the specific dependency you want to manage manually in it, then it
doesn't really matter if the import is in there or not.

It still kinda does tho... I am finding the <Import> still causses issues
regardless if it's empty or not. It still blocks the dotnet pack workflow.
Here's how:

   - git clone https://github.com/bchavez/Bogus --branch vs2017 .\Bogus2
   - cd Bogus2\Source
   - .\.paket\paket.exe install (magic mode!!! thx @forki
   <https://github.com/forki>)
   - cd Bogus
   - dotnet restore ✅ *success*
   - dotnet build ✅ *success*
   - dotnet pack ✅ *success* (when packet.references contains *Newtonsoft*)
   - dotnet restore; dotnet pack ❌ *fail* (when paket.references is
   blank/empty)

Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Bogus -> C:\temp\Bogus2\Source\Bogus\bin\Debug\netstandard1.3\Bogus.dll
  Paket version 4.1.7
  Paket failed with:
        Specified references-file
'C:\temp\Bogus2\Source\Bogus/obj/Bogus.csproj.references' does not
exist.
C:\temp\Bogus2\Source\.paket\Paket.Restore.targets(59,5): error
MSB3073: The command ""C:\temp\Bogus2\Source\.paket\paket.exe"
fix-nuspec file "obj\Bogus.0.0.0-localbuild.nuspec" references-file
"C:\temp\Bogus2\Source\Bogus/obj/Bogus.csproj.references" " exited
with code 1. [C:\temp\Bogus2\Source\Bogus\Bogus.csproj]


   - dotnet pack --include-symbols --include-source ❌ *failure* (when
   paket.references contains *Newtonsoft*)

Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

  Bogus -> C:\temp\Bogus2\Source\Bogus\bin\Debug\netstandard1.3\Bogus.dll
  Paket version 4.1.7
  Paket failed with:
        Specified file
'obj\Bogus.0.0.0-localbuild.nuspec;obj\Bogus.0.0.0-localbuild.symbols.nuspec'
does not exist.
C:\temp\Bogus2\Source\.paket\Paket.Restore.targets(59,5): error
MSB3073: The command ""C:\temp\Bogus2\Source\.paket\paket.exe"
fix-nuspec file
"obj\Bogus.0.0.0-localbuild.nuspec;obj\Bogus.0.0.0-localbuild.symbols.nuspec"
references-file
"C:\temp\Bogus2\Source\Bogus/obj/Bogus.csproj.references" " exited
with code 1. [C:\temp\Bogus2\Source\Bogus\Bogus.csproj]

So, generating nuget packages with symbol info/sources doesn't work and
<Import> still causes problems.

To be totally honest tho... I *just want a way to disable* paket's
injection of <Import> into the csproj so everything works again and I'll
handle everything else in F# FAKE. I would love to continue using Paket +
F# FAKE because of the F# script generation/import still makes a lot of
sense. I just don't want *paket* touching the csprojs when paket.exe install
is called since I keep hitting a lot of friction.

Should just move paket.dependencies off to a sperate folder for F# FAKE
usage? Will that stop *Paket* from touching the *csproj*s?

I'm sorry for being such a bug about this. This stuff is never easy. 😢 Let
me know your thoughts. I (and my users) appreciate your help!

-Brian

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/bchavez/Bogus/pull/68#issuecomment-292306806>, or mute
the thread

**Comment by bchavez** [comment]
Hi @forki ,

I removed `paket.references` from the dotnetcore project folder and `paket.exe install` still adds the `<Import>` as shown in GIF below.

I start off with no `<Import>` use `paket.exe install`, and `<Import>` is still added:

screen_108

**Comment by bchavez** [comment]
Looked deeper into the issue using the **Paket** source code.

**Paket** *will* install into **csproj** regardless if a `paket.references` exists. Pertanant code is here:
https://github.com/fsprojects/Paket/blob/master/src/Paket.Core/RestoreProcess.fs#L124-L136
```
let findAllReferencesFiles root =
    let findRefFile (p:ProjectFile) =
        match p.FindReferencesFile() with
        | Some fileName -> 
                try
                    ok <| (p, ReferencesFile.FromFile fileName)
                with _ ->
                    fail <| ReferencesFileParseError (FileInfo fileName)
        | None ->
            let fileName = 
                let fi = FileInfo(p.FileName)
                Path.Combine(fi.Directory.FullName,Constants.ReferencesFile)

            ok <| (p, ReferencesFile.New fileName)

    ProjectFile.FindAllProjects root 
    |> Array.map findRefFile
    |> collect
```
Specifically, **Line 131**, if no `paket.references` file is found a default / new one is internally created. The `InstallIntoProjects` doesn't distinguish between a reference file that was read `FromFile` or `New`. So, yea, if `paket.references` is not found, it installs `<Import>` anyway.

Let me know if you'd accept a pull request that will respect not installing `<Import>` into **csproj** if `paket.references` does not exist.

Thanks,
Brian

**Pull request merged**
