### PR TITLE
Implement DevSecOps pipeline using GitHub Actions

### PR DESCRIPTION
**Pull request by kulov**
Implement semantic versioning actions using tag generator
Run and publish .NET tests to TestSpace
Implement CI/CD job sequence
Run SonarCloud for static analysis
Run GitHub Dependabot
Run CodeQL rules
Provide CI/CD documentation

### CODE REVIEW

**Comment by kulov** [comment]
Fixes #348

**Comment by bchavez** [comment]
Hello @kulov,

Thank you for submitting a PR. I appreciate the effort you've made here. However, I have some reservations about merging this. This PR is unlikely to be merged for the following reasons:

* This PR adds a significant amount of complexity to the CI/CD pipeline. **This is too much for me to maintain.**
* This PR adds additional build dependencies such as Java.
* This PR uses GitHub actions; I have this feature turned off. I do not plan to re-enable GitHub actions.
* This PR appears to fundamentally change the deployment process by using its own Git tagging system from CI/CD.
  * Currently, I am the one that tags the repository manually with a version number for release because I want to control the exact version of Bogus. The CI/CD system does *not* perform any tagging. This PR appears to be inverting this entire workflow process. Currently, the CI/CD system with AppVeyor is **read-only** and never mutates the Git repository. I would like to keep it this way.
* This PR appears to be using my GitHub token for various operations on GitHub with third-party components I do not trust.
* This PR appears to use third-party services I'm not familiar with. I do not trust these third-party services without a proper vetting first.

Again, I appreciate the level of effort you've put into this PR, but for the reasons above I won't be accepting this PR. In the future, if you'd like to make a change to Bogus, please try creating a GitHub issue first and wait for approval from the maintainer before investing too much work into a PR that might not get merged.

I apologize for rejecting this PR.

Thanks,
Brian

**Comment by kulov** [comment]
Dear @bchavez ,
Please take our apologies. We realize now this is too much of a change proposed.

No worries declining it. It was a learning process for us.
At [Pipeline Foundation](https://pipeline.foundation) we want to help important OSS project like Bogus to help them increase their confidence and maturity to the worlds including enterprises which are willing to use secure and reliable OSS components.

Your feedback on this PR was a great learning experience for us. 
Bogus is our first project at [Pipeline Foundation](https://pipeline.foundation) and we would like to do better!

Would you consider us submitting a new, much smaller, PR where we can show that there is no change in the build process rather it is much more integrated and smooth experience for repo owners and its consumers?

We are committed to deliver great value for you and if you are willing to review and accept our new proposal, we can support the delivery for one year.

Kind regards

**Comment by bchavez** [comment]
Hi @kulov,

Thank you for the response. As far as accepting any PR, I don't know. Please forgive me if the following questions come off as cynical, but I think we'd have to start with the basics:

* What is the **goal**? What is the ***value*** we are trying to achieve with this `DevSecOps` PR?
* How and why is your approach different from GitHub's warning header that is already built into GitHub?
  A warning header that is free and requires no extra work to maintain...
  image

Lastly, 
> we want to help important OSS project like Bogus to help them increase their confidence and maturity to the worlds including enterprises which are willing to use secure and reliable OSS components.

I very much appreciate this. I want the same thing too. I care very much about my users. I will do everything in my power to protect them. However, there is a maximum human limit.

Whatever changes we make cannot come at the cost of hindering, disrupting, or adding complexity to my workflow, build process, source code, or CI/CD pipeline.
  
Fundamentally, and by ***exact*** design, **everything** I have with Bogus is ***low maintenance***. It is the sole reason I can *last* so long maintaining this project without burnout. Also, I'd like to think that the current simple, fast, tight, iterative develop-release process I have with Bogus has contributed to a large part of the success Bogus has had in the .NET world. The "bug identified" to "fixed release" cycle can be measured in minutes with the ease of clicking of a few buttons.

Now, if the enterprise wants an extra layer of "security" added to their build pipeline then the enterprise must bear the cost of any added complexity and maintenance. Under no circumstances will I ***ever*** compromise the ***low maintenance*** I have with Bogus unless I am duly [compensated for it](https://github.com/sponsors/bchavez). I alone cannot bear the added cost of the "needs of the enterprise". I'm a single person, not a team of 200 engineers.
   
Alternatively, the enterprise is free to maintain a fork with their added complexity. If any "security" issues arise, the enterprise can send a PR upstream. I'll be happy to evaluate the enterprise's PR and merge if needed.

This is just to say, there is a fine line and delicate balance between what ***everyone*** wants and what I am ***willing*** to maintain for free.

**Pull request closed without merging**
