### PR TITLE
it-locale extension

### PR DESCRIPTION
**Pull request by supix**
Firstname and Lastname lists have been extended.
Firstnames are 2160.
Lastnames are 3040.

### CODE REVIEW

**Comment by bchavez** [comment]
Hi @supix ,

I appreciate your pull-request and the effort you put into this but there are some major problems with your changes.

* Currently, there are already 362 first names and 100 last names (36,000+ unique) for the `it` locale. Boosting the number of first/last names to 5000+ will add significant weight to **Bogus**. I'm trying to keep the size of the DLL somewhat manageable around **1.5 MB**.

* If you'd like to make changes to existing locale data, your changes should be done upstream and sent to **faker.js** here: https://github.com/Marak/faker.js. Our wiki on the subject can be found here: https://github.com/bchavez/Bogus/wiki/Creating-Locales

* This PR modifies `Bogus/data/it.locale.json` directly. The `Bogus/data/*.locale.json` files are auto-generated and replaced when we update locales from **faker.js**. This means, the next time I update the locales in **Bougs** from **faker.js** upstream, your changes will be overwritten. Data that extends **faker.js'** locales go into the `Bogus/data_extend/*.locale.json` folder. Locales in the `data_extend` folder are merged during the import/update process.

* Your branch is 63 commits behind `master`. Your changes can't be merged due to conflicts. You should rebase on top of `/master` before sending a PR. This will help eliminate merge conflicts.

* Also, I'd recommend creating a GitHub issue before working on a pull-request. This would give everyone in the community a chance to provide feedback, add some discussion on proposed changes, and can help guide you through the source code to better increase your chances of a successful pull-request.

Hope that helps.

Thanks,
Brian

:crown: :gem: ***["I know everything that shine ain't always gold..."](https://www.youtube.com/watch?v=7xzU9Qqdqww)***

**Comment by supix** [comment]
Hi Brian.

Thanks for the useful information. Don't know why my local branch is 63
commits behind. It was directly forked from master. I will check.
Sorry for the confusion. Actually I am using this extended version of
it-locale, because of a project involving large datasets, thus needing a
bigger data population. So I thought it was a good idea to share this
extension. I didn't know of library size issues.

Cheers,
Marcello.

2017-11-15 1:38 GMT+01:00 Brian Chavez <notifications@github.com>:

**Comment by bchavez** [comment]
Hi @supix ,

Thanks for letting me know. If you want **Bogus** to use a larger name list, you can extend the `it` locale with live-patching. Here's an example of how to do that:

https://github.com/bchavez/Bogus/blob/master/Source/Bogus.Tests/BsonTests.cs#L60-L91

Basically, just mutate the `it` locale's `name.first_name` with a `BArray` of names you want to use and Bogus will automatically pick up on the changes and `f => f.Name.FirstName()` will work with your larger name dataset.

Thanks,
Brian

**Comment by supix** [comment]
Nice feature! Thanks.

**Pull request closed without merging**
