### PR TITLE
Improve PickRandom performance

### PR DESCRIPTION
**Pull request by chuuddo**
Current implementation of PickRandom is very slow on big collections.

I propose to implement PickRandom via shuffle

Results of test:
> PickRandom (2 from 2000). Elapsed: 00:00:06.9335806.
> ViaShuffle     (2 from 2000). Elapsed: 00:00:00.2456331.
> 
> PickRandom (10 from 2000). Elapsed: 00:00:08.0522107.
> ViaShuffle (10 from 2000). Elapsed: 00:00:00.3048799.
> 
> PickRandom (100 from 2000). Elapsed: 00:00:08.6209873.
> ViaShuffle (100 from 2000). Elapsed: 00:00:00.8475301.
> 
> PickRandom (500 from 2000). Elapsed: 00:00:09.7293146.
> ViaShuffle (500 from 2000). Elapsed: 00:00:02.8197884.
> 
> PickRandom (1000 from 2000). Elapsed: 00:00:10.7380362.
> ViaShuffle (1000 from 2000). Elapsed: 00:00:05.5229400.
> 
> PickRandom (1999 from 2000). Elapsed: 00:00:12.5223006.
> ViaShuffle (1999 from 2000). Elapsed: 00:00:10.4796257.

Source code of test:
```csharp
internal class Program
{
    private static void Main(string[] args)
    {
        const int childsCount = 2000;
        const int parentsCount = 50000;
        var childsPerParent = new List<int> {2, 10, 100, 500, 1000, 1999};

        var childs = new Faker<Child>().RuleFor(x => x.Id, f =>f.IndexFaker).Generate(childsCount).ToList();

        foreach (var i in childsPerParent)
        {
            Test($"PickRandom ({i} from {childsCount})", 
                new Faker<Parent>().RuleFor(x => x.Childs, f => f.PickRandom(childs, i).ToList()), 
                parentsCount);

            Test($"ViaShuffle ({i} from {childsCount})", 
                new Faker<Parent>().RuleFor(x => x.Childs, f => f.Random.Shuffle(childs).Take(i).ToList()), 
                parentsCount);

            Console.WriteLine();
            GC.Collect();
        }
        Console.ReadLine();
    }

    private static void Test(string testName, Faker<Parent> parentFaker, int parentsCount)
    {
        var sw = Stopwatch.StartNew();
        var parents = parentFaker.Generate(parentsCount).ToList();
        Console.WriteLine($"{testName}. Elapsed: {sw.Elapsed}.");
    }

    private class Parent
    {
        public List<Child> Childs { get; set; }
    }

    private class Child
    {
        public int Id { get; set; }
    }
}
```

### CODE REVIEW

**Comment by bchavez** [comment]
Hi @chuuddo, very interesting find. Thanks for this PR.

At first glance, I would have thought the first algorithm would have performed better. Do you have any insights on why that is? Either way, really nice optimization.

Also wrote a quick [BenchmarkDotNet to test your findings](https://github.com/bchavez/Bogus/blob/master/Source/Benchmark/BenchRandomSubset.cs). Seems legit:

benchrandomsubset-barplot

``` ini

BenchmarkDotNet=v0.10.3.0, OS=Microsoft Windows NT 6.1.7601 Service Pack 1
Processor=Intel(R) Core(TM) i7-3960X CPU 3.30GHz, ProcessorCount=12
Frequency=3224619 Hz, Resolution=310.1142 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1590.0
  DefaultJob : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1590.0


```
 |      Method | Selections |        Mean |    StdDev |
 |------------ |----------- |------------ |---------- |
 |  **PickRandom** |          **2** | **107.1595 us** | **0.5795 us** |
 | ShuffleTake |          2 |   1.0538 us | 0.0036 us |
 |  **PickRandom** |         **10** | **127.5909 us** | **0.2363 us** |
 | ShuffleTake |         10 |   1.7135 us | 0.0039 us |
 |  **PickRandom** |        **100** | **136.2395 us** | **0.0761 us** |
 | ShuffleTake |        100 |   8.2667 us | 0.0139 us |
 |  **PickRandom** |        **500** | **148.7440 us** | **0.1608 us** |
 | ShuffleTake |        500 |  34.6432 us | 0.1936 us |
 |  **PickRandom** |       **1000** | **158.4600 us** | **0.2454 us** |
 | ShuffleTake |       1000 |  67.0757 us | 0.1214 us |
 |  **PickRandom** |       **1999** | **174.8529 us** | **1.1987 us** |
 | ShuffleTake |       1999 | 133.7551 us | 1.0093 us |


IIRC, @joelharkes , originally contribiuted the `PickRandom` subset algorithm in #49 and #51.

Thanks @chuuddo. If you test any more benchmark improvments, feel free to add them to the [`Benchmark` project here](https://github.com/bchavez/Bogus/tree/master/Source/Benchmark) so we can keep a nice catalog of benchmarks. :) 

Thanks,
Brian

:headphones: :notes: ***[Antiserum & Mayhem - Trippy](https://www.youtube.com/watch?v=o95ZTp5fuF8)***

**Comment by joelharkes** [comment]
Ah nice work. I didn't know shuffle() was that optimized.

**Comment by chuuddo** [comment]
Hi @bchavez.
old PickRandom is O(n), where n = items count.
Shuffle.Take is O(m), where m = amount to pick.
This is the main reason why ShuffleTake is more perfomant than old PickRandom.

Another reason.
old PickRandom used Int() method, that implemented through Seed.NextDouble() 
Shuffle() implemented through Seed.Next(), as well as Number().
``` ini

BenchmarkDotNet=v0.10.3.0, OS=Microsoft Windows NT 6.1.7601 Service Pack 1
Processor=Intel(R) Core(TM) i3-2120 CPU 3.30GHz, ProcessorCount=4
Frequency=3215449 Hz, Resolution=310.9986 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1590.0
  DefaultJob : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1590.0


```
 | Method |       Mean |    StdDev |
 |------- |----------- |---------- |
 |    Int | 67.8891 ns | 0.0155 ns |
 | Number | 49.6898 ns | 0.0168 ns |

benchrandomint-barplot

**Comment by joelharkes** [comment]
I see, how does the shuffle mechanism provide protection against getting same item multiple times? 
does it remove it form a temporary stored array or something?

**Comment by chuuddo** [comment]
@joelharkes Shuffle() uses modern version of the Fisher–Yates shuffle, u can see how it works here: [https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_modern_algorithm](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_modern_algorithm)

**Pull request merged**
