### PR TITLE
Update projects

### PR DESCRIPTION
**Pull request by SimonCropp**
* move to new sdk style csproj for benchmark and tests
 * add support for running benchmarks and tests on netcoreapp2.0
 * remove redundant assemblyinfo from benchmark and tests

### CODE REVIEW

**Comment by mortware** [comment]
This might be unrelated to updating the project but I think I need this for my current .NET Core application. It seems to work on my dev machine, but TC seems to have a problem fetching the Bogus nuget package.
`Unable to load the service index for source https://api.nuget.org/v3/index.json.`

**Comment by bchavez** [comment]
Hi @mortware ,

Yea, I think your issue is unrelated to the changes in this PR. It looks like most of Simon's changes in this PR are related to Bogus' test and benchmarking projects. The test/benchmark projects aren't published on NuGet. Bogus proper is already using the new csproj / dotnet project file.

The error seems more like a NuGet tooling issue. What version of NuGet are you using? Have you tried looking here?
https://github.com/NuGet/Home/issues/2880
https://github.com/NuGet/Home/issues/5358
https://github.com/dotnet/corefx/issues/30354

**Comment by mortware** [comment]
Hi, Yeah -
After a few days of TC build failures, our DevOps guy sheepishly approached
me and said it was all his fault - so false alarm! nothing to see here. As
you were :)
David (mortware)

**Comment by bchavez** [comment]
Hey Simon,

Thanks again Simon for all the help! :)

Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Pull request merged**
