### PR TITLE
Initialize Randomizer with Random

### PR DESCRIPTION
**Pull request by howardwang0620**
Allows Randomizer's global random `Seed` to stay consistent with usages of randoms in outer scopes.

### CODE REVIEW

**Comment by bchavez** [comment]
@howardwang0620 can you please allow edits to this PR?

**Comment by howardwang0620** [comment]
> @howardwang0620 can you please allow edits to this PR?

Not sure where I can do that, don't see the "Allow edits from maintainers" option. Can you see the contents of the PR?

**Comment by bchavez** [comment]
Hi @howardwang0620, I can see the contents of the PR; however,
* I'd like to add an associated unit test along with the PR.
* I'd like to rename `rand` to `localSeed`.
* And make some minor improvements to XML docs in the general area.

I tried making the edits, but GitHub denied it. I suspect it might be because the PR looks like it originates from an organizational account, not `howardwang0620`; but not totally sure.

This probably won't get merged as-is, especially without an accompanying unit test. If you want to write one, please see the `GitHub` folder in the test project, and please adhere to all coding conventions.

**Comment by howardwang0620** [comment]
> This probably won't get merged as-is, especially without an accompanying unit test. If you want to write one, please see the `GitHub` folder in the test project, and please adhere to all coding conventions.

Gotcha, closing and will make a new PR for this change

**Pull request closed without merging**
