### PR TITLE
Generate GB Registration Plates

### PR DESCRIPTION
**Pull request by colinangusmackay**
This adds an extension (`GbRegistrationPlate`) method to the `Bogus.Extensions.UnitedKingdom` namespace to generate licence plates for GB vehicles.

Generates:
* Plates for the current registration scheme (running from 2001 until 2051).
* Plates registered in geographic locations cross the island of Great Britain.
* Applies the following special cases:
  * Export plates.
  * Edinburgh mid-2007 plates.

Limitations:
* Current scheme only. 
* Excludes Northern Ireland.
* Does not produce all the possibilities for "cherished" plates. (i.e. custom/personalised plate) which are a superset of the main rules.
* Excludes plates for kit/custom-build vehicles.
* Can sometimes produce plates which the DVLA consider "rude" and would normally be excluded on a case-by-case basis.

### CODE REVIEW

**Comment by colinangusmackay** [comment]
Hmm... I'm not sure why that test is failing. My change was purely additive, and should not have affected other tests. I've also run all the tests on my machine and they all pass there.

From AppVeyor:
```
Bogus.Tests.HandleBarTests.parse_test Bogus.Tests.DLL (.NETFramework,Version=v4.7.1) 134 ms
Error message:
Expected string to be 
"Mitchell, Bernhard DDS" with a length of 22, but 
"Barton, Emilia V" has a length of 16.
Error stack trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstLengthDifferences()
   at FluentAssertions.Primitives.StringValidator.Validate()
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs)
   at Bogus.Tests.HandleBarTests.parse_test() in C:\projects\bogus\Source\Bogus.Tests\HandleBarTests.cs:line 23
Std OUT:
"Barton, Emilia V"
```

**Comment by colinangusmackay** [comment]
Phew! 😅 Got there in the end.

**Comment by bchavez** [comment]
Hi Colin,

Wow. Well done! Amazing PR! Picture perfect! Truly, great job!

I should have a new release for you shortly!

**Comment by colinangusmackay** [comment]
Thanks for pushing this out to NuGet so quickly. I really appreciate it.

**Comment by bchavez** [comment]
Hey Colin, no problem. It's the least I can do for you in exchange for the great work in your PR. Also, we move pretty fast here in the Bogus repo. `/master` is always ready for tagging a release at any time.

Also, sorry for those flaky tests. I've been having a few issues with flaky tests myself. Been hunting them down last few releases. I hope f21c0739e0c85a3d43d0e4b57e98de8502e4bcd9 might have finally corrected the issue. :crossed_fingers:

**Comment by TAGC** [comment]
Thought it was awfully convenient when I was planning to use Bogus to generate fake vehicles for Commissions and saw there was already a built-in option for generating GB licence plates. :D

**Pull request merged**
