### PR TITLE
Add UK National Insurance Number

### PR DESCRIPTION
**Pull request by mortware**
Does not follow strict rules for valid leading characters (i.e. D, F, I, Q, U or V are not valid)

### CODE REVIEW

**Comment by bchavez** [comment]
Hi David,

Is a NINO number the same as a NIN number?

I found a few open source NINO generators:
https://github.com/corbanworks/fng-nino-tools/blob/master/fngnino.js

https://github.com/hmrc/domain/blob/eecf5a5169a9f2205cc89def487e0b9121fd5af8/src/main/scala/uk/gov/hmrc/domain/Nino.scala

I'm thinking we can adapt one of those to C# and have this `Nin` generator generate valid leading and ending characters (and possibly pass validation checks).

Let me know.

Thanks,
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***

**Comment by mortware** [comment]
Hi Brian,

Yes it seems that tool provides all the validation needed, and is a more
complete example. I had intended to fit something like that in when I had a
chance :)
This wiki article describes the validation:
https://en.wikipedia.org/wiki/National_Insurance_number

Would you like me to port it across?

David

**Comment by bchavez** [comment]
Hi David,

Porting one of them to C# would be really great if you have enough time.

If you don't have time, I'll go ahead and just merge your PR as-is. Something is better than nothing! :+1: 

It's good to know there's some code out there that we can use, for future reference :sunglasses:  

Let me know,
Brian

:chocolate_bar: :cookie: :lollipop: [**Ronald Jenkees - Stay Crunchy**](https://www.youtube.com/watch?v=GeIAXlwVlZc)

**Comment by bchavez** [comment]
Hey David,

Are we okay to merge `.Nino()`?

I might make a small modification to the algorithm, instead of having a `do{}while{}` loop to check for valid prefixes, I'll replace an invalid prefix with a known good one (like `DP`). :sunglasses: 

Normally, I like to keep the generation algorithms a "one-shot" deal to keep deterministic behavior somewhat stable and repeatable. If we draw from `Random` too many times in loops, it can make it hard sometimes to debug and track down deterministic issues.

Regardless though, you've done a great job here and look forward to merging this! :+1: :1st_place_medal: 

Thanks again for your contribution!
Brian

:boom: :fire: ***["Set it ablaze like a candle wick... Light it up, light it up..."](https://www.youtube.com/watch?v=qDcFryDXQ7U)***

**Comment by bchavez** [comment]
Hi David,

Your code changes are live in [**`Bogus v22.3.1`**](https://www.nuget.org/packages/Bogus/22.3.1)! :tada: 

Thanks again for helping with this!
Brian

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***

**Comment by mortware** [comment]
Hey Brian,
Great changes! I'm sure they will perform a lot better too. Glad I could help.
David

**Pull request merged**
